//자주묻는질문

const faqPosts = [
  {
    id: 1,
    sort: "이용방법",
    title: "주문앱으로 배달 가능한가요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 2,
    sort: "계정",
    title: "회원가입을 하면 어떤 장점이 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 3,
    sort: "이용방법",
    title: "비회원으로 주문이 가능한가요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 4,
    sort: "점포",
    title: "제 주변에 있는 한솥 점포를 어떻게 찾을 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 5,
    sort: "점포",
    title: "점포 영업시간은 어디서 확인 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 6,
    sort: "이용방법",
    title: "주문앱의 혜택이 무엇인가요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 7,
    sort: "계정",
    title: "회원정보는 어떻게 업데이트 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 8,
    sort: "이용방법",
    title: "주문앱으로 결제 방법은 무엇이 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 9,
    sort: "계정",
    title: "로그아웃은 어떻게 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 10,
    sort: "이용방법",
    title: "주문앱으로 주문하면 언제 음식이 만들어지나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 11,
    sort: "계정",
    title: "주문내역은 어디서 확인 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 12,
    sort: "이용방법",
    title: "주문앱으로 주문 수량 제한이 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 13,
    sort: "계정",
    title: "비밀번호를 잊었습니다. 어떻게 해야 되나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 14,
    sort: "이용방법",
    title: "주문앱으로 주문한 음식은 언제 픽업 하면 되나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 15,
    sort: "이용방법",
    title: "주문 넣은 후 주문 수정 가능한가요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 16,
    sort: "이용방법",
    title: "주문 취소는 어떻게 하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 17,
    sort: "이용방법",
    title: "주문앱으로 단체주문은 어떻게 하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 18,
    sort: "이용방법",
    title: "주문앱을 이용한 주문은 몇시 부터 몇시 까지 가능하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 19,
    sort: "이용방법",
    title: "점포에 도착 후 도시락은 어떻게 픽업 하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 20,
    sort: "이용방법",
    title: "주문앱으로 후불 가능한가요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 21,
    sort: "이용방법",
    title: "비회원 주문 내역은 어디서 확인하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 22,
    sort: "이용방법",
    title: "결제를 완료했는데 메뉴를 추가하고 싶어요.",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 23,
    sort: "이용방법",
    title: "픽업 시간 알림이 따로 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 24,
    sort: "이용방법",
    title: "점포에 도착 후 도시락은 어떻게 픽업 하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 25,
    sort: "결제",
    title: "결제 PIN번호를 잊어버렸습니다.",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 26,
    sort: "결제",
    title: "왜 와이파이로는 결제가 되지않나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 27,
    sort: "결제",
    title: "결제가 이중으로 되었어요. 어떻게 해야 하나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 28,
    sort: "계정",
    title: "회원정보는 어떻게 업데이트 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 29,
    sort: "계정",
    title: "가입시 만들었던 아이디를 변경할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 30,
    sort: "계정",
    title: "회원 탈퇴 후 재가입을 할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
  {
    id: 31,
    sort: "쿠폰",
    title: "모바일 시식권을 쿠폰으로 사용할 수 있나요?",
    icon: "images/content/frequently_asked/arrow_right.png",
  },
];

export { faqPosts };

// 고객의 소리
export let seoulArr = [
  "군/구 선택",
  "강남구",
  "강동구",
  "강북구",
  "강서구",
  "관악구",
  "광진구",
  "구로구",
  "금천구",
  "노원구",
  "도봉구",
  "동대문구",
  "동작구",
  "마포구",
  "서대문구",
  "서초구",
  "성동구",
  "성북구",
  "송파구",
  "양천구",
  "영등포구",
  "용산구",
  "은평구",
  "종로구",
  "중구",
  "중랑구",
];

export let incheonArr = [
  "군/구 선택",
  "계양구",
  "남구",
  "남동구",
  "동구",
  "부평구",
  "서구",
  "연수구",
  "중구",
  "강화군",
  "옹진군",
];

export let daejeonArr = [
  "군/구 선택",
  "대덕구",
  "동구",
  "서구",
  "유성구",
  "중구",
];
export let gwangjuArr = [
  "군/구 선택",
  "광산구",
  "남구",
  "동구",
  "북구",
  "서구",
];
export let daeguArr = [
  "군/구 선택",
  "남구",
  "달서구",
  "동구",
  "북구",
  "서구",
  "수성구",
  "중구",
  "달성군",
];

export let ulsanArr = ["군/구 선택", "남구", "동구", "북구", "중구", "울주군"];

export let busanArr = [
  "군/구 선택",
  "강서구",
  "금정구",
  "남구",
  "동구",
  "동래구",
  "부산진구",
  "북구",
  "사상구",
  "사하구",
  "서구",
  "수영구",
  "연제구",
  "영도구",
  "중구",
  "해운대구",
  "기장군",
];

export let gyeonggiArr = [
  "군/구 선택",
  "고양시",
  "과천시",
  "광명시",
  "광주시",
  "구리시",
  "군포시",
  "김포시",
  "남양주시",
  "동두천시",
  "부천시",
  "성남시",
  "수원시",
  "시흥시",
  "안산시",
  "안성시",
  "안양시",
  "양주시",
  "오산시",
  "용인시",
  "의왕시",
  "의정부시",
  "이천시",
  "파주시",
  "평택시",
  "포천시",
  "하남시",
  "화성시",
  "가평군",
  "양평군",
  "여주군",
  "연천군",
];

export let gwangwonArr = [
  "군/구 선택",
  "강릉시",
  "동해시",
  "삼척시",
  "속초시",
  "원주시",
  "춘천시",
  "태백시",
  "고성군",
  "양구군",
  "양양군",
  "영월군",
  "인제군",
  "정선군",
  "철원군",
  "평창군",
  "홍천군",
  "화천군",
  "횡성군",
];

export let northCungcheongArr = [
  "군/구 선택",
  "제천시",
  "청주시",
  "충주시",
  "괴산군",
  "단양군",
  "보은군",
  "영동군",
  "옥천군",
  "음성군",
  "증평군",
  "진천군",
  "청원군",
];

export let southCungcheongArr = [
  "군/구 선택",
  "계룡시",
  "공주시",
  "논산시",
  "보령시",
  "서산시",
  "아산시",
  "천안시",
  "금산군",
  "당진군",
  "부여군",
  "서천군",
  "연기군",
  "예산군",
  "청양군",
  "태안군",
  "홍성군",
];

export let northJeonraArr = [
  "군/구 선택",
  "군산시",
  "김제시",
  "남원시",
  "익산시",
  "전주시",
  "정읍시",
  "고창군",
  "무주군",
  "부안군",
  "순창군",
  "완주군",
  "임실군",
  "장수군",
  "진안군",
];
export let southJeonraArr = [
  "군/구 선택",
  "광양시",
  "나주시",
  "목포시",
  "순천시",
  "여수시",
  "강진군",
  "고흥군",
  "곡성군",
  "구례군",
  "담양군",
  "무안군",
  "보성군",
  "신안군",
  "영광군",
  "영암군",
  "완도군",
  "장성군",
  "장흥군",
  "진도군",
  "함평군",
  "해남군",
  "화순군",
];
export let northGyeongsangArr = [
  "군/구 선택",
  "경산시",
  "경주시",
  "구미시",
  "김천시",
  "문경시",
  "상주시",
  "안동시",
  "영주시",
  "영천시",
  "포항시",
  "고령군",
  "군위군",
  "봉화군",
  "성주군",
  "영덕군",
  "영양군",
  "예천군",
  "울릉군",
  "울진군",
  "의성군",
  "청도군",
  "청송군",
  "칠곡군",
];
export let southGyeongsangArr = [
  "군/구 선택",
  "거제시",
  "김해시",
  "마산시",
  "밀양시",
  "사천시",
  "양산시",
  "진주시",
  "진해시",
  "창원시",
  "통영시",
  "거창군",
  "고성군",
  "남해군",
  "산청군",
  "의령군",
  "창녕군",
  "하동군",
  "함안군",
  "함양군",
  "합천군",
];
export let jejuArr = [
  "군/구 선택",
  "서귀포시",
  "제주시",
  "남제주군",
  "북제주군",
];
